"""Constants for the dataset profiler package."""

from __future__ import annotations

MAX_TOP_VALUES = 5
SEMANTIC_SAMPLE_SIZE = 100
HIGH_CARDINALITY_RATIO_THRESHOLD = 0.9
CATEGORICAL_RATIO_THRESHOLD = 0.2
MAX_FREQUENCY_INFERENCE_UNIQUE_VALUES = 1000
HIGH_MISSING_PERCENTAGE_THRESHOLD = 50.0
VERY_HIGH_MISSING_PERCENTAGE_THRESHOLD = 80.0
VERY_HIGH_CARDINALITY_RATIO_THRESHOLD = 0.95
BOOLEAN_CONFIDENCE_THRESHOLD = 0.9
SEMANTIC_CONFIDENCE_THRESHOLD = 0.8
SEMANTIC_HIGH_CONFIDENCE_THRESHOLD = 0.9
COUNTRY_MATCH_THRESHOLD = 0.6
AGE_MAX_VALUE = 120
TEXT_LENGTH_MINIMUM = 1
TEXT_LENGTH_MAXIMUM = 64
TEMPORAL_DIMENSION_MIN_UNIQUE_VALUES = 2

SEMANTIC_TYPE_UNKNOWN = "Unknown"
SEMANTIC_TYPE_NUMERIC = "Numeric"
SEMANTIC_TYPE_CATEGORICAL = "Categorical"
SEMANTIC_TYPE_TEXT = "Text"
SEMANTIC_TYPE_BOOLEAN = "Boolean"
SEMANTIC_TYPE_DATETIME = "Datetime"
SEMANTIC_TYPE_ID = "ID"

SEMANTIC_TYPE_NUMERIC_SET = {SEMANTIC_TYPE_NUMERIC}
SEMANTIC_TYPE_DATETIME_SET = {SEMANTIC_TYPE_DATETIME}
SEMANTIC_TYPE_CATEGORICAL_SET = {SEMANTIC_TYPE_CATEGORICAL, SEMANTIC_TYPE_ID}

ROLE_KEY = "key"
ROLE_MEASURE = "measure"
ROLE_DIMENSION = "dimension"
ROLE_DATETIME = "datetime"
ROLE_FLAG = "flag"
ROLE_TEXT = "text"
ROLE_UNKNOWN = "unknown"
