"""Code validator for AI-generated Python code."""

from __future__ import annotations

import ast
import logging
from dataclasses import dataclass
from typing import List, Set

from .constants import FORBIDDEN_FUNCTIONS, FORBIDDEN_IMPORT_MODULES, REQUIRED_OUTPUT_VARIABLE
from .exceptions import (
    ForbiddenFunctionError,
    ForbiddenImportError,
    ForbiddenModuleError,
    MissingFigureError,
    SyntaxValidationError,
    ValidationError,
)
from .models import ValidatedCode

logger = logging.getLogger(__name__)


class _ValidatorLogger:
    """Keeps validation logging separate from validation logic."""

    def __init__(self, logger: logging.Logger) -> None:
        self._logger = logger

    def validation_started(self) -> None:
        self._logger.info("Code validation started")

    def syntax_passed(self) -> None:
        self._logger.info("Syntax validation passed")

    def imports_passed(self) -> None:
        self._logger.info("Import validation passed")

    def functions_passed(self) -> None:
        self._logger.info("Function validation passed")

    def modules_passed(self) -> None:
        self._logger.info("Module validation passed")

    def figure_passed(self) -> None:
        self._logger.info("Figure assignment validation passed")

    def validation_completed(self, is_valid: bool) -> None:
        self._logger.info("Validation completed (valid=%s)", is_valid)


class CodeValidator:
    """Validate AI-generated Python code against the execution contract.

    Checks:
    1. Valid Python syntax
    2. No import statements
    3. No forbidden built-in functions
    4. No forbidden module references
    5. Assignment to required output variable `fig`
    """

    def __init__(self) -> None:
        self._events = _ValidatorLogger(logger)

    def validate(self, python_code: str) -> ValidatedCode:
        """Validate generated Python code.

        Args:
            python_code: The Python code generated by Gemini.

        Returns:
            ValidatedCode with is_valid=True if all checks pass,
            or is_valid=False with error messages if any check fails.
        """
        self._events.validation_started()
        errors: List[str] = []

        # 1. Syntax validation
        try:
            tree = ast.parse(python_code)
            self._events.syntax_passed()
        except SyntaxError as exc:
            errors.append(f"Syntax error: {exc}")
            self._events.validation_completed(False)
            return ValidatedCode(python_code=python_code, is_valid=False, errors=tuple(errors))

        # 2. Import validation
        import_errors = self._check_imports(tree)
        if import_errors:
            errors.extend(import_errors)
        else:
            self._events.imports_passed()

        # 3. Function validation
        function_errors = self._check_functions(tree)
        if function_errors:
            errors.extend(function_errors)
        else:
            self._events.functions_passed()

        # 4. Module reference validation
        module_errors = self._check_module_references(tree)
        if module_errors:
            errors.extend(module_errors)
        else:
            self._events.modules_passed()

        # 5. Figure assignment validation
        if not self._check_fig_assignment(tree):
            errors.append(f"Code must assign the final figure to '{REQUIRED_OUTPUT_VARIABLE}'")
        else:
            self._events.figure_passed()

        is_valid = len(errors) == 0
        self._events.validation_completed(is_valid)

        return ValidatedCode(
            python_code=python_code,
            is_valid=is_valid,
            errors=tuple(errors),
        )

    def _check_imports(self, tree: ast.AST) -> List[str]:
        """Check for forbidden import statements."""

        errors: List[str] = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    errors.append(f"Forbidden import: {alias.name}")
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    errors.append(f"Forbidden import: from {node.module}")
        return errors

    def _check_functions(self, tree: ast.AST) -> List[str]:
        """Check for forbidden function calls."""

        errors: List[str] = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func_name = self._get_function_name(node.func)
                if func_name in FORBIDDEN_FUNCTIONS:
                    errors.append(f"Forbidden function call: {func_name}()")
        return errors

    def _check_module_references(self, tree: ast.AST) -> List[str]:
        """Check for forbidden module name references in attribute access."""

        errors: List[str] = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Attribute):
                if isinstance(node.value, ast.Name):
                    module_name = node.value.id
                    if module_name in FORBIDDEN_IMPORT_MODULES:
                        errors.append(f"Forbidden module reference: {module_name}")
        return errors

    def _check_fig_assignment(self, tree: ast.AST) -> bool:
        """Check that the code assigns to the required output variable."""

        for node in ast.walk(tree):
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and target.id == REQUIRED_OUTPUT_VARIABLE:
                        return True
        return False

    @staticmethod
    def _get_function_name(node: ast.AST) -> str:
        """Extract function name from a call node."""

        if isinstance(node, ast.Name):
            return node.id
        if isinstance(node, ast.Attribute):
            return node.attr
        return ""